### ISSUE TITLE
OOI自动登入失效？[Bug回報]

### ISSUE THREAD

**Issue by M3351AN** [ming900518/KC2CHT#5]
**敘述問題**
当选择使用OOI进行游戏时，无论是否启用自动登入都无法自动登入

**設備型號（請務必附上）**
 - 裝置名稱 iPhone 6s Plus
 - iOS版本 iOS 13.6
 - 使用的App版本 1.0 (TW.CHT-Release2.6)

**Comment by ming900518** [comment]
剛剛實測Release 2.6功能正常

自動登入功能是用Javascript實現的，需要等候注入
正常情況下需等待10秒，跟網路品質有關
